### ISSUE TITLE
老哥那个pull点错了，不好意思，另外我想知道一下yml传入的参数

### ISSUE THREAD

**Issue by biubiu10086** [zhangjinbao520/BaWangCan_Actions#2]
cityId
NICKNAME

**Comment by biubiu10086** [comment]
已经可以了，我已经试出来了，感谢大佬
![图片](https://user-images.githubusercontent.com/32834058/108937356-9954ca00-7689-11eb-856e-c17826d1c81c.png)

**Comment by zhangjinbao3114** [comment]
yml传入的参数为自定义的，后续我更新在README里面说明叭
