### ISSUE TITLE
有些店铺的branchId为None仍会导致报名失败

### ISSUE THREAD

**Issue by ushio20** [zhangjinbao520/BaWangCan_Actions#9]
branchId为空即“”时提交仍有些店铺不能选择分店

**Comment by zhangjinbao3114** [comment]
由于部分免费试需要橙 V 才能点亮，已修订优化

**Comment by ushio20** [comment]
是的我是试了你的最新代码，橙v也会有些分店选择失败，提示请选择分店

**Comment by ushio20** [comment]
大约三分之二分店可选，三分之一分店不可以，我看了下请求url=https://m.dianping.com/mobile/dinendish/apply/getPreApply的返回结果，branchId有的为""就可以选择，branchId为None的就不能选择分店

**Comment by ushio20** [comment]
大约三分之二分店可选，三分之一分店不可以，我看了下请求url=https://m.dianping.com/mobile/dinendish/apply/getPreApply 的返回结果，branchId有的为""就可以选择，branchId为None的就不能选择分店
